name: Python Notes App Image Build
on:
  push:
    branches:
      - "main"
env:
  IMAGE_REPO: "ghcr.io/${{ github.actor }}"
  IMG_TAG: "0.0.0"
  APP_NAME: "python-notes-app"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build_image:
    runs-on: ubuntu-latest
    name: Building Container Image
    steps:
      - name: Checkingout 
        uses: actions/checkout@v2
      - name: Loging to ghcr.io 
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ env.IMAGE_REPO }}/${{ env.APP_NAME }}:${{ env.IMG_TAG }}